services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: ai-analytics-postgres

    environment:
      POSTGRES_DB: ai_analytics
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_password

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data: